//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "category")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub category_code: String,
    pub category_name: String,
    pub parent_code: String,
    pub level: i16,
    pub leaf: bool,
    pub source_code: String,
    pub source_system: String,
    pub data_state: i16,
    pub create_time: Option<DateTimeWithTimeZone>,
    pub update_time: Option<DateTimeWithTimeZone>,
    pub category_type: i16,
    pub path_code: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub ext: Json,
    pub create_by: String,
    pub update_by: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
