//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "company")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub org_code: String,
    #[sea_orm(unique)]
    pub company_code: String,
    pub company_name: String,
    pub company_type: i16,
    pub register_type: i16,
    pub register_capital: String,
    #[sea_orm(unique)]
    pub usci_code: String,
    pub legal_person: String,
    pub establish_time: Option<Date>,
    pub address: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub finance_info: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub ext: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub attachments: Json,
    pub data_state: i16,
    pub create_by: String,
    pub update_by: String,
    pub create_time: DateTimeWithTimeZone,
    pub update_time: DateTimeWithTimeZone,
    pub tax_type: i16,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
