//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "menu_manager")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub menu_version: String,
    pub menu_time: Option<DateTime>,
    #[sea_orm(column_type = "JsonBinary")]
    pub attachments: Json,
    pub comment: String,
    pub data_state: i16,
    pub create_time: DateTime,
    pub create_by: String,
    pub update_time: DateTime,
    pub update_by: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
