//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod prelude;

pub mod bank;
pub mod bank_branch;
pub mod category;
pub mod commercial_area;
pub mod company;
pub mod menu_manager;
pub mod org;
pub mod product;
pub mod product_asset;
pub mod product_image;
pub mod product_sku;
pub mod product_sku_material;
pub mod product_spu;
pub mod shop;
pub mod shop_0625;
pub mod shop_asset;
pub mod shop_attachment;
pub mod shop_finance;
pub mod shop_tmp;
pub mod supplier;
pub mod supplier_account;
pub mod supplier_finance_bank;
pub mod supplier_product;
pub mod supplier_test;
