//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "product_sku_material")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub sku_code: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub unit_config: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub switch_config: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub ext: Json,
    pub create_by: String,
    pub update_by: String,
    pub create_time: Option<DateTimeWithTimeZone>,
    pub update_time: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
