//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "product_sku")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub spu_code: String,
    #[sea_orm(unique)]
    pub sku_code: String,
    pub mnemonic: String,
    pub sku_name: String,
    pub category_code: String,
    pub barcode: String,
    pub min_unit: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub ext: Json,
    pub source_code: String,
    pub source_system: String,
    pub data_state: i16,
    pub create_by: String,
    pub update_by: String,
    pub create_time: Option<DateTimeWithTimeZone>,
    pub update_time: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
