//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "product_spu")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub realm: String,
    #[sea_orm(unique)]
    pub spu_code: String,
    pub mnemonic: String,
    pub spu_name: String,
    pub spu_type: i16,
    pub display_name: String,
    pub category_code: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub spec_fields: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub ext: Json,
    pub source_code: String,
    pub source_system: String,
    pub data_state: i16,
    pub create_by: String,
    pub update_by: String,
    pub create_time: DateTimeWithTimeZone,
    pub update_time: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
