//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "shop")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub org_code: String,
    pub shop_code: String,
    pub shop_name: String,
    pub display_name: String,
    pub shop_type: i16,
    pub business_status: i16,
    pub business_type: i16,
    pub mnemonic: String,
    pub taxpayer_nature: i16,
    pub company_code: String,
    pub location_code: String,
    pub open_date: DateTimeWithTimeZone,
    pub property_type: i16,
    pub floor: i16,
    pub unit_number: String,
    #[sea_orm(column_type = "Decimal(Some((12, 6)))")]
    pub area_size: Decimal,
    #[sea_orm(column_type = "Decimal(Some((12, 6)))")]
    pub outside_area_size: Decimal,
    pub country: String,
    pub region: String,
    pub province: String,
    pub city: String,
    pub district: String,
    pub address: String,
    #[sea_orm(column_type = "Decimal(Some((9, 6)))")]
    pub lng: Decimal,
    #[sea_orm(column_type = "Decimal(Some((9, 6)))")]
    pub lat: Decimal,
    #[sea_orm(column_type = "Decimal(Some((9, 6)))")]
    pub bd_lng: Decimal,
    #[sea_orm(column_type = "Decimal(Some((9, 6)))")]
    pub bd_lat: Decimal,
    #[sea_orm(column_type = "JsonBinary")]
    pub contacts: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub ext: Json,
    pub data_state: i16,
    pub create_by: String,
    pub update_by: String,
    pub create_time: DateTimeWithTimeZone,
    pub update_time: DateTimeWithTimeZone,
    pub seat_number: i16,
    pub property_company: String,
    pub project_grade: i16,
    pub project_property_status: i16,
    pub commercial_area_code: String,
    pub uc_org_code: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
