//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "shop_tmp")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub shop_code: String,
    pub shop_name: String,
    pub manage_type: String,
    #[sea_orm(column_type = "Decimal(Some((10, 6)))")]
    pub lng: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 6)))")]
    pub lat: Decimal,
    pub province: String,
    pub city: String,
    pub district: String,
    #[sea_orm(column_type = "Decimal(Some((18, 2)))")]
    pub store_area: Decimal,
    pub capacity: i32,
    pub point_count: i32,
    pub def_capacity: i32,
    pub emp_count: i32,
    pub store_opened_duration: String,
    pub total_sales_grade: String,
    pub manage_region: String,
    pub org_path_code: String,
    pub org_path_name: String,
    pub create_time: DateTimeWithTimeZone,
    pub update_time: DateTimeWithTimeZone,
    pub manage_area: String,
    pub region_manager_code: String,
    pub region_manager_name: String,
    pub area_manager_code: String,
    pub area_manager_name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
