//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "commercial_area")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub province_code: String,
    pub city_code: String,
    pub district_code: String,
    #[sea_orm(unique)]
    pub area_code: String,
    pub area_name: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub area_types: Json,
    pub priority: i16,
    #[sea_orm(column_type = "JsonBinary")]
    pub ext: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub attachments: Json,
    pub data_state: i16,
    pub create_by: String,
    pub update_by: String,
    pub create_time: DateTime,
    pub update_time: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
