//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "product")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub realm: String,
    #[sea_orm(unique)]
    pub product_code: String,
    pub product_type: i16,
    pub product_sub_type: i16,
    pub product_name: String,
    pub display_name: String,
    pub category_code: String,
    pub combine_type: i16,
    pub combine_main_code: String,
    pub combine_rule: String,
    pub barcode: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub ext: Json,
    pub data_state: i16,
    pub create_by: String,
    pub update_by: String,
    pub create_time: DateTimeWithTimeZone,
    pub update_time: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
