//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "supplier_account")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub supplier_code: String,
    pub user_code: String,
    pub phone: String,
    pub name: String,
    pub comment: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub ext: Json,
    pub data_state: i16,
    pub create_by: String,
    pub update_by: String,
    pub create_time: DateTimeWithTimeZone,
    pub update_time: DateTimeWithTimeZone,
    #[sea_orm(column_type = "JsonBinary")]
    pub r#type: Json,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
