//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "supplier_finance_bank")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub supplier_code: String,
    pub bank_code: String,
    pub bank_branch_code: String,
    pub bank_account: String,
    pub bank_account_name: String,
    pub create_time: DateTime,
    pub update_time: DateTime,
    pub base_account_number: String,
    pub tax_type: i16,
    pub invoice_type: i16,
    pub tax_rate: i16,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
